global:
  ansible_playbook: ansible/playbook.yaml
  ansible_verbose: vvvv
  bastion_user: user
  bastion_host: host

roles:
  fedora:
    box: fedora/24-cloud-base
  devstack-host:
    provider_host: host
    provider_user: root
    storage_pool_name: volumes
  devstack:
    ansible_groups:
      - devstack
  network-devstack:
    public_network:
      - type: bridge
        dev: some-bridge
        ip: 1.1.1.%<item>s
    private_network:
      - ip: 10.0.%<item>s.2
  memory-low:
    memory: 4096
    cpus: 1
  memory-medium:
    memory: 8192
    cpus: 1
  memory-high:
    memory: 16384
    cpus: 1
  karbor:
    devstack_local_conf:
      local.conf.karbor
  devstack-karbor:
    roles:
      - fedora
      - memory-medium
      - devstack
      - network-devstack
      - karbor

machines:
  devstack:
    type: range
    start: 111
    count: 4
    roles:
      - devstack-host
      - devstack-karbor
  devstack-116:
    roles:
      - devstack-host
      - devstack-karbor
    memory: 4096
  test-range:
    type: range
    roles:
      - devstack-host
      - fedora

