global:
  ansible-playbook: ansible/playbook.yaml
  bastion_user: user
  bastion_host: host

roles:
  fedora:
    box: fedora/24-cloud-base
  devstack-host:
    provider_host: user
    provider_username: root
    storage_pool_name: volumes
  network-devstack:
    public_network:
      - type: bridge
        dev: some-bridge
        ip: 1.1.1.%<item>s
    private_network:
      - ip: 10.0.%<item>s.2
  memory-light:
    memory: 4096
    cpus: 1
  memory-medium:
    memory: 8192
    cpus: 1
  memory-high:
    memory: 16384
    cpus: 1
  ansible-karbor:
    ansible_args:
      local-conf: local.conf.karbor
    ansible_groups:
      - devstack
  devstack-karbor:
    roles:
      - fedora
      - memory-medium
      - network-devstack
      - memory-medium
      - ansible-karbor

machines:
  ~range-devstack:
    ~start: 111
    ~count: 3
    devstack-%<item>s:
      roles:
        - devstack-host
        - devstack-karbor
  devstack-115:
    roles:
      - devstack-karbor
    memory: 4096
    ansible_host_vars:
      test: 1

