---
- name: obtain devstack
  become: yes
  become_user: stack
  git:
    repo: https://github.com/openstack-dev/devstack
    dest: /opt/stack/devstack

- name: set local.conf
  template:
    src: "{{ devstack_local_conf }}"
    dest: /opt/stack/devstack/local.conf
    owner: stack
    group: stack

- name: run devstack
  become: yes
  become_user: stack
  shell: ./stack.sh &> /opt/stack/devstack.log
  args:
    chdir: /opt/stack/devstack
    creates: /opt/stack/status/stack
