---
- name: obtain devstack
  become: yes
  become_user: stack
  git:
    repo: https://git.openstack.org/openstack-dev/devstack
    dest: /opt/stack/devstack

- name: set local.conf
  template:
    src: "{{ devstack_local_conf }}"
    dest: /opt/stack/devstack/local.conf
    owner: stack
    group: stack

- name: run devstack
  become: yes
  become_user: stack
  shell: ./stack.sh &> /opt/stack/devstack.log
  args:
    chdir: /opt/stack/devstack
    creates: /opt/stack/status/stack

- name: enable horizon cinder backups
  ignore_errors: True
  replace:
    dest: /opt/stack/horizon/openstack_dashboard/local/local_settings.py
    backup: yes
    regexp: 'OPENSTACK_CINDER_FEATURES = {[\s]*''enable_backup'': (False|True)(,|)[\s]*}'
    replace: 'OPENSTACK_CINDER_FEATURES = {''enable_backup'': True}'
