---
- name: upgrade dnf
  dnf: name=dnf state=latest
- name: dnf update
  dnf: name='*' state=latest
- name: install basic tools
  dnf: name={{item}} state=present
  with_items:
    - tmux
    - python-pip
    - vim-minimal
    - vim
    - xauth
    - tigervnc
    - git
    - the_silver_searcher
- name: install kernel dev
  dnf: name=kernel-devel state=present
- name: install python devel
  dnf: name={{item}} state=present
  with_items:
    - python-tox
    - python-subunit
